package create.excel.enums;

public enum BSSheetConstants {
	NUM_COLUMNS(19), BS_DATE(4), CURRENCY_TYPE(5), NET_EQUITY_COLUMN(6), NET_EQUITY_GROWTH_COLUMN(7),
	SHARE_HOLDER_EQUITY_COLUMN(8), SHARE_HOLDER_EQUITY_GROWTH_COLUMN(9), INTANGIBLE_ASSETS_COLUMN(10),
	CASH_AND_CASH_EQUIVALENT_COLUMN(11), SHORT_TERM_INVESTMENTS_COLUMN(12), RECEIVABLES_COLUMN(13),
	LONG_TERM_INVESTMENTS_COLUMN(14), SHORT_TERM_DEBT_COLUMN(15), ACCOUNTS_PAYABLE_COLUMN(16),
	LONG_TERM_DEBT_COLUMN(17), LAST_COLUMN(18), FIRST_BS_YEAR(1), SECOND_BS_YEAR(2), THIRD_BS_YEAR(3),
	FOURTH_BS_YEAR(4), FIFTH_BS_YEAR(5);

	private Integer bsData;

	private BSSheetConstants(Integer bsCol) {
		this.bsData = bsCol;
	}

	public Integer getBSData() {
		return bsData;
	}

}
